#
# Site settings
#
# remote_theme: LeakyAbstractions/pretty-docs
url: https://css-sise.github.io
# baseurl: /
title: &site_title SISE.5351&#58; Computational Social Science
description: &site_description Class website for SISE.5351&#58; Computational Social Science
branding:
  icon:
    name: social_dribbble_square
  highlight: <br>SISE.5351
  bold: <br><br>Computational Social Science
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true
github: [metadata]
future: true
#
# Owner
#
owner:
  name: Nir Grinberg
  twitter: &site_owner_twitter grinbergnir
  copyright:
    notice: All rights reserved.
    author: "[Nir Grinberg](https://nirg.net/)"


#
# Social
#
open_graph:
  title: *site_title
  site_name: *site_title
  description: *site_description
  locale: en_US
  image: /assets/images/css-main-web.jpg
twitter_cards:
  title: *site_title
  description: *site_description
  creator: *site_owner_twitter
  card: summary_large_image
  image: /assets/images/css-main-web.jpg
share:
  facebook:
    class: fb-like
    action: like
    layout: button_count
    show-faces: false
    share: false
  twitter:
    via: *site_owner_twitter
    text: &site_description
    title: Tweet
  github:
    repo: css-sise/css-sise.github.io
    position: right
    color: gray


# Google Analytics
# google_analytics: UA-61670496-5


#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc

exclude: [ 'README.md', 'CHANGELOG.md' ]
